[package]
name = "virtual-deque"
version = "0.1.0"
authors = ["gnzlbg <gonzalobg88@gmail.com>"]

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "macos")'.dependencies]
mach = "0.1.*"

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'